import "./globals.css";

import { AppContext, Web3Modal } from "./contexts";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Navbar } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Training DApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark text-foreground bg-background md:px-10 px-3"
    >
      <body>
        <Web3Modal>
          <AppContext>
            <div>
              <Navbar />
              {children}
            </div>
          </AppContext>
        </Web3Modal>
      </body>
    </html>
  );
}
